language: ruby
rvm:
- ruby-2.2.2
env:
  global: 
deploy:
  provider: heroku
  api_key:
    secure: PtF9rHhEhVGtNcaknXgyx9LMyx24ex6KxdrCEufChLDYEmyLpOXAWBqvERmPbNSXDug9mOjWAoarJnNwp0Qm0fb/CEnC82vE23jsC4Hxc71FVQq09txsZ/JezSmr2KIcBBDxhwgRI8KtRJquM3C2C7b1M4jNkxM9PITWagbeGTKmEfGoq06leufyFw0GLmbPlDP/uX5bIzojmLLLtAHI4LXj4e01Y6KuugeckzjvX2P2bQKYZkTVsDyk4vi124bUYn9T0YtDjDNKKiTF605YVbkq01PZ8baiAsba4vT+U5kOEtQfUg7bwPJZ6IEN7oq9x+cPFvLk01rIY6TnYbxVsj2D2HczSSjErQ7PgR2TqCyDWeZgRGj2yAgQjb3mNuqI2B8tMCXlmiZGGkjS4kd1dMgtAliB0pQ0EiZ2bA7LvU5xyrCjTs+g2VhGkVE6Nt/7JlDb0wsY0mQYIlzuvZeNuADdmOmyAoLmowVxPQSKy9yNR777eagutY/2BL5tq/PjzAtHZ1Xc0AEmOHNVQpAISGs/ZUEL4w17V8JTTQutDGrITlaIy4BHinDrKqsRnQ6XhygMH70ihwDgy1pvNndXIUp4a6S3Mpo1JlHFQ4Aik9PkaxCeawe2kHAEPbR68CGb/AasCOgP626u++7r2wMGisXONJs96NacVq2ATaVKXz8=
  app: terciar-rendicionesbo
  on:
    repo: Terciar/cubaRendicionLaboratorio
