language: ruby
rvm:
- ruby-2.2.0
env:
  global: 
deploy:
  provider: heroku
  api_key:
    secure: TuKH/dqcMP2mNar3TxQmtvNZJ37vCt2niffwfmUUt4qFVz+NW4yiDzX5Egj0qPwFyIZYqSEkz9frrmXV9Yodd0yCLL/PPS8dbGGlPUT3r2eNFW4VsAmOJLEFlS44DUKfAANrPFLsu5m/drrq0P9xo0mxupqfWPG30n8rX8wGZkEuNoxQ5EgelmcEDmrY4rp9/2ptcNADKDh1KgXpsMefeOrNXmRKjYEXQgJggHx67Z+zROSTUQnhIJmMWD7jX9mWvsHrYkIs2ulIc8sSB8KDHeHbhm/E1xRW8jvorAZP/8vydItMwZT8fVmku1cmX+wytv2uWCbHChQdxI9k4QkL52h/YxcFX03MuyO5/Tmcb5Xtp6Iw5jrg/lDhKMtLYwbcjL+ZHZxHJBdJ59kNelh3F/U91zQG9yJjyPxYt2wtZsVS8kHoU0B3tyVNyrmcZs88VM8ubCXkax7YZMTCc9Aj6LlNFgIkCQEKHSic0gP5D7dxcrszewaImXPMZoxLq31ZGhpUCecflpZHP+bC8x/veAudOuUeQTAS37goEkBFm98gweI2ZqrVhwmVs8w6hjli0Ad3i8NOwm+r0/lLaF3n8L2A5lJkq5jv5+4nmbJx1hyRLBfikKVIqY+A9PP8C3moiDdcZqQua++ryMPrsAN6PCw/iMiiOrxRFYZfRMCuDxk=
  app: terciar-cubalab
  on:
    repo: matiasmasca/cubaRendicionLaboratorio
